import{supabase}from"./supabase.js";const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),date=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";let requests=[],current=null;

async function load(){$("loading").style.display="block";grid.innerHTML="";$("empty").style.display="none";$("error").classList.remove("active");try{let{data,error}=await supabase.from("accessible_car_requests").select("*").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}

function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>(x.status||"new")==="new").length;$("progressRequests").textContent=requests.filter(x=>x.status==="in-progress").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length;$("cancelledRequests").textContent=requests.filter(x=>x.status==="cancelled").length}

function render(){let q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,o=$("sortFilter").value,l=requests.filter(x=>{let t=`${x.full_name||""} ${x.phone||""} ${x.email||""} ${x.vehicle||""} ${x.mobility_need||""}`.toLowerCase();return(!q||t.includes(q))&&(s==="all"||(x.status||"new")===s)});l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}grid.innerHTML=l.map(x=>{let st=x.status||"new";return`<article class="request-card" onclick="openRequest('${x.id}')"><div class="request-top"><span class="request-status ${esc(st)}">${esc(st)}</span><small>${date(x.created_at)}</small></div><h3>${esc(x.full_name||"Unnamed Customer")}</h3><p><i class="fa-solid fa-phone"></i> ${esc(x.phone||"—")}</p><p><i class="fa-solid fa-envelope"></i> ${esc(x.email||"—")}</p><div class="request-meta"><span>${esc(x.vehicle_type||"Accessible Vehicle")}</span><strong>${esc(x.mobility_need||"Requirement not specified")}</strong></div><div class="request-bottom"><span>${esc(x.preferred_contact||"Contact via phone")}</span><button type="button" onclick="event.stopPropagation();openRequest('${x.id}')">View Request <i class="fa-solid fa-arrow-right"></i></button></div></article>`}).join("")}

window.openRequest=id=>{current=requests.find(x=>x.id===id);if(!current)return;$("modalTitle").textContent=`${current.full_name||"Customer"}'s Request`;$("modalStatus").value=current.status||"new";$("modalBody").innerHTML=`<div class="detail-grid"><div><span>Full Name</span><strong>${esc(current.full_name)}</strong></div><div><span>Phone / WhatsApp</span><strong>${esc(current.phone||"—")}</strong></div><div><span>Email</span><strong>${esc(current.email||"—")}</strong></div><div><span>Vehicle Type</span><strong>${esc(current.vehicle_type||"—")}</strong></div><div><span>Mobility Requirement</span><strong>${esc(current.mobility_need||"—")}</strong></div><div><span>Preferred Contact</span><strong>${esc(current.preferred_contact||"—")}</strong></div><div><span>Budget</span><strong>${esc(current.budget||"—")}</strong></div><div><span>Submitted</span><strong>${date(current.created_at)}</strong></div></div><div class="notes"><span>Additional Information</span><p>${esc(current.message||current.notes||"No additional information.")}</p></div>`;$("requestModal").classList.add("show");document.body.classList.add("locked")};

async function saveStatus(){if(!current)return;let status=$("modalStatus").value,{error}=await supabase.from("accessible_car_requests").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}

async function deleteRequest(){if(!current||!confirm(`Delete request from ${current.full_name||"this customer"}?`))return;let{error}=await supabase.from("accessible_car_requests").delete().eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}

function closeRequest(){$("requestModal").classList.remove("show");document.body.classList.remove("locked");current=null}

$("searchInput").oninput=render;$("statusFilter").onchange=render;$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));load();