import{supabase}from"./supabase.js";import{requireAdmin}from"./admin-guard.js";import{markSectionSeen}from"./badges.js";import{attachBadges}from"./admin-nav.js";
const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),fmt=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";
let requests=[],current=null;
async function load(){$("loading").style.display="block";grid.innerHTML="";$("empty").style.display="none";$("error").classList.remove("active");$("error").textContent="";try{const{data,error}=await supabase.from("accessible_car_requests").select("*").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}
function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>(x.status||"new")==="new").length;$("progressRequests").textContent=requests.filter(x=>x.status==="in-progress").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length;$("cancelledRequests").textContent=requests.filter(x=>x.status==="cancelled").length}
function render(){const q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,o=$("sortFilter").value;let l=requests.filter(x=>{const t=`${x.full_name||""} ${x.phone||""} ${x.email||""} ${x.location||""} ${x.disability_type||""} ${x.vehicle_type||""} ${x.budget||""} ${x.ncpwd||""} ${x.modifications||""} ${x.additional_requirements||""} ${x.purchase_method||""} ${x.timeline||""}`.toLowerCase();return(!q||t.includes(q))&&(s==="all"||(x.status||"new")===s)});l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}grid.innerHTML=l.map(x=>{const st=x.status||"new",mods=Array.isArray(x.modifications)?x.modifications.join(", "):(x.modifications||"None");return`<article class="request-card" data-id="${esc(x.id)}"><div class="request-top"><span class="request-status ${esc(st)}">${esc(st)}</span><small>${fmt(x.created_at)}</small></div><h3>${esc(x.full_name||"Unnamed Customer")}</h3><p><i class="fa-solid fa-phone"></i> ${esc(x.phone||"No phone")}</p><p><i class="fa-solid fa-envelope"></i> ${esc(x.email||"No email")}</p><div class="request-meta"><span>${esc(x.vehicle_type||"Vehicle not specified")}</span><strong>${esc(x.budget||"Budget not set")}</strong></div><div class="request-bottom"><span>${esc(x.disability_type||"Need not specified")}</span><button type="button">View <i class="fa-solid fa-arrow-right"></i></button></div></article>`}).join("");grid.querySelectorAll(".request-card").forEach(c=>c.addEventListener("click",()=>openRequest(c.dataset.id)));grid.querySelectorAll(".request-bottom button").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();openRequest(b.dataset.id)}))}
function detail(label,value){return`<div><span>${label}</span><strong>${esc(value||"—")}</strong></div>`}
function openRequest(id){current=requests.find(x=>String(x.id)===String(id));if(!current)return;$("modalTitle").textContent=`${current.full_name||"Customer"}'s Request`;$("modalSubtitle").textContent=`Submitted ${fmt(current.created_at)}`;$("modalStatus").value=current.status||"new";
$("customerDetails").innerHTML=detail("Full Name",current.full_name)+detail("Phone / WhatsApp",current.phone)+detail("Email",current.email)+detail("Location",current.location)+detail("NCPWD Certificate",current.ncpwd)+detail("Purchase Method",current.purchase_method)+detail("Timeline",current.timeline)+detail("Submitted",fmt(current.created_at));
$("vehicleName").textContent=current.vehicle_type||"Accessible Vehicle";$("vehicleSpecs").textContent=current.disability_type||"Accessibility requirements";
$("vehicleDetails").innerHTML=detail("Vehicle Type",current.vehicle_type)+detail("Accessibility Need",current.disability_type)+detail("Budget",current.budget)+detail("NCPWD Certificate",current.ncpwd)+detail("Purchase Method",current.purchase_method)+detail("Timeline",current.timeline)+detail("Last Updated",fmt(current.updated_at));
$("customerNotes").innerHTML=`<span>Additional Requirements</span><p>${esc(current.additional_requirements||"No additional requirements provided.")}</p>`;
const mods=Array.isArray(current.modifications)?current.modifications.join(", "):(current.modifications||"No specific modifications provided.");$("requirementNotes").innerHTML=`<span>Required Modifications</span><p>${esc(mods)}</p>`;
let actions=[];if(current.phone){const raw=String(current.phone).replace(/\D/g,""),wa=raw.startsWith("254")?raw:raw.startsWith("0")?`254${raw.slice(1)}`:`254${raw}`,tel=raw.startsWith("254")?`+${raw}`:raw.startsWith("0")?`+254${raw.slice(1)}`:`+254${raw}`;actions.push(`<a class="call-btn" href="tel:${esc(tel)}"><i class="fa-solid fa-phone"></i> Call Customer</a>`);actions.push(`<a class="whatsapp-btn" href="https://wa.me/${esc(wa)}" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a>`);actions.push(`<button class="copy-btn" type="button" id="copyPhone"><i class="fa-solid fa-copy"></i> Copy Phone</button>`)}if(current.email)actions.push(`<a class="email-btn" href="mailto:${esc(current.email)}"><i class="fa-solid fa-envelope"></i> Email Customer</a>`);$("contactActions").innerHTML=actions.join("");
$("copyPhone")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(current.phone);$("copyPhone").innerHTML='<i class="fa-solid fa-check"></i> Copied';setTimeout(()=>$("copyPhone").innerHTML='<i class="fa-solid fa-copy"></i> Copy Phone',1200)}catch{}});$("requestModal").classList.add("show");document.body.classList.add("locked")}
async function saveStatus(){if(!current)return;const status=$("modalStatus").value,{error}=await supabase.from("accessible_car_requests").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}
async function deleteRequest(){if(!current||!confirm(`Delete request from ${current.full_name||"this customer"}?`))return;const{error}=await supabase.from("accessible_car_requests").delete().eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}
function closeRequest(){$("requestModal").classList.remove("show");document.body.classList.remove("locked");current=null}
$("searchInput").oninput=render;$("statusFilter").onchange=render;$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;
$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("requestModal").classList.contains("show"))closeRequest()});window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));requireAdmin("accessiblecars").then(ok=>{if(ok){load();markSectionSeen("accessiblecars");attachBadges()}});