import{supabase}from"./supabase.js";const BUCKET="car-images",p=new URLSearchParams(location.search),carId=p.get("id"),$=id=>document.getElementById(id),form=$("carForm"),loading=$("loading"),di=$("displayInput"),gi=$("galleryInput"),dp=$("displayPreview"),gp=$("galleryPreview");let car=null,gallery=[],newDisplay=null,removeDisplay=false;
const fields=["make","model","trim","year","price","condition","body_type","status","engine_size","engine_description","horsepower","mileage","exterior_color","interior_color","seats","doors","vin","chassis_number","registration_number","stock_number","country_of_origin","import_year","registration_year","auction_grade","previous_owners","accident_history","service_history","number_of_keys","inspection_status","inspection_notes","location","city","county","description"],nums=new Set(["year","price","engine_size","horsepower","mileage","seats","doors","import_year","registration_year","previous_owners","number_of_keys"]);
const msg=(id,t)=>{$(id).textContent=t;$(id).classList.add("active")},clear=()=>{$("error").classList.remove("active");$("success").classList.remove("active")},url=path=>supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl,safe=n=>n.toLowerCase().replace(/[^a-z0-9.]+/g,"-");
async function load(){if(!carId){loading.textContent="No vehicle ID provided.";return}try{let{data,error}=await supabase.from("cars").select("*").eq("id",carId).single();if(error)throw error;car=data;fields.forEach(id=>$(id)&&($(id).value=car[id]??""));$("negotiable").checked=!!car.negotiable;$("financing_available").checked=!!car.financing_available;$("test_drive_available").checked=car.test_drive_available!==false;$("featured").checked=!!car.featured;if(car.display_image_url)showDisplay(car.display_image_url);let r=await supabase.from("car_images").select("*").eq("car_id",carId).order("display_order",{ascending:true});if(r.error)throw r.error;gallery=r.data||[];renderGallery();form.style.display="block"}catch(e){loading.textContent=e.message}finally{loading.style.display="none"}}
function showDisplay(u){dp.innerHTML=`<img src="${u}" alt="Display image">`;dp.classList.add("active");$("removeDisplay").classList.add("active")}
function renderGallery(){gp.innerHTML="";gallery.forEach(img=>{let x=document.createElement("div");x.className="gallery-item";x.innerHTML=`<img src="${img.image_url}" alt="Vehicle gallery"><button type="button" class="delete-image"><i class="fa-solid fa-xmark"></i></button><button type="button" class="make-main">Make Display</button>`;x.querySelector(".delete-image").onclick=()=>deleteImage(img,x);x.querySelector(".make-main").onclick=()=>makeMain(img);gp.appendChild(x)})}
di.onchange=e=>{newDisplay=e.target.files[0]||null;removeDisplay=false;if(newDisplay)showDisplay(URL.createObjectURL(newDisplay))};$("removeDisplay").onclick=()=>{newDisplay=null;removeDisplay=true;di.value="";dp.innerHTML="";dp.classList.remove("active");$("removeDisplay").classList.remove("active")};
gi.onchange=e=>{[...e.target.files].forEach(uploadGallery);gi.value=""};
async function uploadGallery(file){try{let path=`${carId}/gallery/${crypto.randomUUID()}-${safe(file.name)}`,u=await supabase.storage.from(BUCKET).upload(path,file,{cacheControl:"3600",upsert:false});if(u.error)throw u.error;let r=await supabase.from("car_images").insert({car_id:carId,image_url:url(path),storage_path:path,image_type:"gallery",display_order:gallery.length}).select().single();if(r.error)throw r.error;gallery.push(r.data);renderGallery()}catch(e){msg("error",e.message)}}
async function deleteImage(img,item){if(!confirm("Delete this gallery image?"))return;try{if(img.storage_path){let r=await supabase.storage.from(BUCKET).remove([img.storage_path]);if(r.error)throw r.error}let r=await supabase.from("car_images").delete().eq("id",img.id);if(r.error)throw r.error;gallery=gallery.filter(x=>x.id!==img.id);renderGallery()}catch(e){msg("error",e.message)}}
async function saveDisplay(u,path){let{error}=await supabase.from("cars").update({display_image_url:u,display_image_path:path}).eq("id",carId);if(error)throw error;car.display_image_url=u;car.display_image_path=path}
async function makeMain(img){try{await saveDisplay(img.image_url,img.storage_path);showDisplay(img.image_url);msg("success","Gallery image is now the display image.")}catch(e){msg("error",e.message)}}
async function uploadDisplay(){if(!newDisplay)return;let old=car.display_image_path,path=`${carId}/display/${crypto.randomUUID()}-${safe(newDisplay.name)}`,r=await supabase.storage.from(BUCKET).upload(path,newDisplay,{cacheControl:"3600",upsert:false});if(r.error)throw r.error;await saveDisplay(url(path),path);if(old)await supabase.storage.from(BUCKET).remove([old])}
form.onsubmit=async e=>{e.preventDefault();clear();$("saveBtn").disabled=true;$("saveBtn").textContent="Saving...";try{let updates={};fields.forEach(id=>updates[id]=nums.has(id)?($(id).value.trim()===""?null:Number($(id).value)):($(id).value.trim()===""?null:$(id).value));updates.negotiable=$("negotiable").checked;updates.financing_available=$("financing_available").checked;updates.test_drive_available=$("test_drive_available").checked;updates.featured=$("featured").checked;if(newDisplay){await uploadDisplay();newDisplay=null}if(removeDisplay){if(car.display_image_path)await supabase.storage.from(BUCKET).remove([car.display_image_path]);updates.display_image_url=null;updates.display_image_path=null}updates.updated_at=new Date().toISOString();let{error}=await supabase.from("cars").update(updates).eq("id",carId);if(error)throw error;car={...car,...updates};removeDisplay=false;msg("success","Vehicle saved successfully.");$("saveBtn").textContent="Saved";setTimeout(()=>$("saveBtn").textContent="Save Changes",1000)}catch(e){msg("error",e.message);$("saveBtn").textContent="Save Changes"}finally{$("saveBtn").disabled=false}};
$("deleteBtn").onclick=async()=>{if(!confirm("Delete this vehicle and all its images?"))return;try{$("deleteBtn").disabled=true;let paths=[car.display_image_path,...gallery.map(x=>x.storage_path)].filter(Boolean);if(paths.length)await supabase.storage.from(BUCKET).remove(paths);let{error}=await supabase.from("cars").delete().eq("id",carId);if(error)throw error;location.href="index.html"}catch(e){msg("error",e.message);$("deleteBtn").disabled=false}};
$("backBtn").onclick=$("cancelBtn").onclick=$("bottomCancel").onclick=()=>location.href="index.html";load();