import{supabase}from"./supabase.js";
import{requireAdmin}from"./admin-guard.js";const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),money=v=>Number(v||0).toLocaleString("en-KE"),fmt=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";let requests=[],current=null;
async function load(){$("loading").style.display="block";grid.innerHTML="";$("empty").style.display="none";try{let{data,error}=await supabase.from("import_requests").select("*").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}
function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>x.status==="new").length;$("progressRequests").textContent=requests.filter(x=>x.status==="in-progress").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length}
function render(){let q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,o=$("sortFilter").value,l=requests.filter(x=>`${x.full_name||""} ${x.phone||""} ${x.email||""} ${x.make||""} ${x.model||""} ${x.country||""}`.toLowerCase().includes(q)&&(s==="all"||x.status===s));l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):o==="budget-high"?(b.budget||0)-(a.budget||0):o==="budget-low"?(a.budget||0)-(b.budget||0):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}grid.innerHTML=l.map(x=>`<article class="request-card" onclick="openRequest('${x.id}')"><div class="request-top"><span class="request-status ${esc(x.status||"new")}">${esc(x.status||"new")}</span><small>${fmt(x.created_at)}</small></div><h3>${esc(x.full_name)}</h3><p><i class="fa-solid fa-phone"></i> ${esc(x.phone)}</p><p><i class="fa-solid fa-car"></i> ${esc(x.make)} ${esc(x.model||"")}</p><div class="request-meta"><span>${esc(x.country)}</span><strong>KES ${money(x.budget)}</strong></div><div class="request-bottom"><span>${esc(x.timeline)}</span><button type="button" onclick="event.stopPropagation();openRequest('${x.id}')">View Request <i class="fa-solid fa-arrow-right"></i></button></div></article>`).join("")}
window.openRequest=id=>{current=requests.find(x=>x.id===id);if(!current)return;$("modalTitle").textContent=`${current.full_name}'s Request`;$("modalStatus").value=current.status||"new";$("modalBody").innerHTML=`<div class="detail-grid"><div><span>Full Name</span><strong>${esc(current.full_name)}</strong></div><div><span>Phone / WhatsApp</span><strong>${esc(current.phone)}</strong></div><div><span>Email</span><strong>${esc(current.email||"—")}</strong></div><div><span>Country of Origin</span><strong>${esc(current.country)}</strong></div><div><span>Preferred Make</span><strong>${esc(current.make)}</strong></div><div><span>Preferred Model</span><strong>${esc(current.model||"—")}</strong></div><div><span>Year From</span><strong>${esc(current.year||"—")}</strong></div><div><span>Budget</span><strong>KES ${money(current.budget)}</strong></div><div><span>Timeline</span><strong>${esc(current.timeline)}</strong></div><div><span>Submitted</span><strong>${fmt(current.created_at)}</strong></div></div><div class="notes"><span>Additional Notes</span><p>${esc(current.notes||"No additional notes.")}</p></div>`;$("requestModal").classList.add("show");document.body.classList.add("locked")}
async function saveStatus(){if(!current)return;let status=$("modalStatus").value,{error}=await supabase.from("import_requests").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);current.status=status;closeRequest();load()}
async function deleteRequest(){if(!current||!confirm(`Delete import request from ${current.full_name}?`))return;let{error}=await supabase.from("import_requests").delete().eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}
function closeRequest(){$("requestModal").classList.remove("show");document.body.classList.remove("locked");current=null}
$("searchInput").oninput=render;$("statusFilter").onchange=render;$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));requireAdmin("imports").then(x=>x&&load());