import{supabase}from"./supabase.js";
import{requireAdmin}from"./admin-guard.js";
const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),fmt=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";
let requests=[],current=null;
async function load(){$("loading").style.display="block";$("error").textContent="";$("error").classList.remove("active");grid.innerHTML="";$("empty").style.display="none";try{const{data,error}=await supabase.from("insurance_requests").select("*").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){console.error(e);$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}
function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>x.status==="new").length;$("contactedRequests").textContent=requests.filter(x=>x.status==="contacted").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length}
function render(){const q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,o=$("sortFilter").value;let l=requests.filter(x=>`${x.full_name||""} ${x.phone||""} ${x.email||""} ${x.registration||""} ${x.vehicle||""} ${x.cover||""}`.toLowerCase().includes(q)&&(s==="all"||x.status===s));l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}grid.innerHTML=l.map(x=>`<article class="request-card" data-id="${x.id}"><div class="request-top"><span class="request-status ${esc(x.status||"new")}">${esc(x.status||"new")}</span><small>${fmt(x.created_at)}</small></div><h3>${esc(x.full_name)}</h3><p><i class="fa-solid fa-phone"></i> ${esc(x.phone)}</p><p><i class="fa-solid fa-car"></i> ${esc(x.registration)} · ${esc(x.vehicle||"Vehicle")}</p><div class="request-meta"><span>${esc(x.cover||"—")}</span><strong>${esc(x.contact_method||"Phone Call")}</strong></div><div class="request-bottom"><span>${esc(x.email||"No email")}</span><button type="button" data-view="${x.id}">View Request <i class="fa-solid fa-arrow-right"></i></button></div></article>`).join("");grid.querySelectorAll(".request-card").forEach(c=>c.onclick=()=>openRequest(c.dataset.id));grid.querySelectorAll("[data-view]").forEach(b=>b.onclick=e=>{e.stopPropagation();openRequest(b.dataset.view)})}
async function openRequest(id){current=requests.find(x=>x.id===id);if(!current)return;$("modalTitle").textContent=`${current.full_name}'s Request`;$("modalStatus").value=current.status||"new";$("modalBody").innerHTML=`<div class="detail-grid"><div><span>Full Name</span><strong>${esc(current.full_name)}</strong></div><div><span>Phone</span><strong>${esc(current.phone)}</strong></div><div><span>Email</span><strong>${esc(current.email||"—")}</strong></div><div><span>Contact Method</span><strong>${esc(current.contact_method||"—")}</strong></div><div><span>Registration</span><strong>${esc(current.registration)}</strong></div><div><span>Vehicle</span><strong>${esc(current.vehicle||"—")}</strong></div><div><span>Year</span><strong>${esc(current.year||"—")}</strong></div><div><span>Cover</span><strong>${esc(current.cover||"—")}</strong></div><div><span>Consent</span><strong>${current.consent?"Accepted":"Not Accepted"}</strong></div><div><span>Submitted</span><strong>${fmt(current.created_at)}</strong></div></div><div class="documents"><span>Customer Documents</span><div class="document-grid"><button class="document-btn" type="button" data-doc="logbook_path"><i class="fa-solid fa-file-pdf"></i> Logbook</button><button class="document-btn" type="button" data-doc="id_copy_path"><i class="fa-solid fa-id-card"></i> ID / Passport</button><button class="document-btn" type="button" data-doc="kra_pin_path"><i class="fa-solid fa-file-shield"></i> KRA PIN</button></div></div>${current.admin_notes?`<div class="notes"><span>Admin Notes</span><p>${esc(current.admin_notes)}</p></div>`:""}`;$("requestModal").classList.add("show");document.body.classList.add("locked");document.querySelectorAll("[data-doc]").forEach(b=>b.onclick=()=>openDocument(b.dataset.doc))}
async function openDocument(field){if(!current?.[field])return alert("Document not found.");const{data,error}=await supabase.storage.from("insurance-documents").createSignedUrl(current[field],300);if(error)return alert(error.message);window.open(data.signedUrl,"_blank","noopener,noreferrer")}
async function saveStatus(){if(!current)return;const status=$("modalStatus").value,{error}=await supabase.from("insurance_requests").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}
async function deleteRequest(){if(!current||!confirm(`Delete insurance request from ${current.full_name}?`))return;const paths=[current.logbook_path,current.id_copy_path,current.kra_pin_path].filter(Boolean),{error}=await supabase.from("insurance_requests").delete().eq("id",current.id);if(error)return alert(error.message);if(paths.length)await supabase.storage.from("insurance-documents").remove(paths);closeRequest();load()}
function closeRequest(){$("requestModal").classList.remove("show");document.body.classList.remove("locked");current=null}
$("searchInput").oninput=render;$("statusFilter").onchange=render;$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));requireAdmin("insurance").then(x=>x&&load());