import{supabase}from"./supabase.js";import{requireAdmin}from"./admin-guard.js";import{markSectionSeen}from"./badges.js";import{attachBadges}from"./admin-nav.js";
const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),fmt=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";
const money=v=>v===null||v===undefined||v===""?null:`KES ${Number(v).toLocaleString()}`;
let requests=[],current=null;
async function load(){$("loading").style.display="block";$("error").textContent="";$("error").classList.remove("active");grid.innerHTML="";$("empty").style.display="none";try{const{data,error}=await supabase.from("insurance_requests").select("*").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){console.error(e);$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}
function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>x.status==="new").length;$("contactedRequests").textContent=requests.filter(x=>x.status==="contacted").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length}
function render(){const q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,c=$("categoryFilter")?.value||"all",o=$("sortFilter").value;let l=requests.filter(x=>`${x.full_name||""} ${x.phone||""} ${x.email||""} ${x.registration||""} ${x.vehicle||""} ${x.cover||""} ${x.contact_method||""} ${x.insurance_type||""} ${x.location||""} ${x.description||""}`.toLowerCase().includes(q)&&(s==="all"||x.status===s)&&(c==="all"||(x.insurance_category||"MOTOR")===c));l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}$("empty").style.display="none";grid.innerHTML=l.map(x=>{const cat=x.insurance_category||"MOTOR",isMotor=cat==="MOTOR",catLabel=isMotor?"Motor":"Non-Motor",catClass=isMotor?"motor":"nonmotor",line2=isMotor?{icon:"fa-car",value:x.registration||"No registration"}:{icon:"fa-shield-halved",value:x.insurance_type||"Type not specified"},metaSpan=isMotor?(x.cover||"Cover not specified"):(x.location||x.cover_required_date||"Insurance enquiry");return`<article class="request-card" data-id="${esc(x.id)}"><div class="request-top"><div class="request-top-badges"><span class="request-category ${catClass}">${esc(catLabel)}</span><span class="request-status ${esc(x.status||"new")}">${esc(x.status||"new")}</span></div><small>${fmt(x.created_at)}</small></div><h3>${esc(x.full_name||"Unnamed Customer")}</h3><p><i class="fa-solid fa-phone"></i> ${esc(x.phone||"No phone")}</p><p><i class="fa-solid ${line2.icon}"></i> ${esc(line2.value)}</p><div class="request-meta"><span>${esc(metaSpan)}</span><strong>${esc(x.contact_method||"Phone Call")}</strong></div><div class="request-bottom"><span>${esc(x.email||"No email")}</span><button type="button">View <i class="fa-solid fa-arrow-right"></i></button></div></article>`}).join("")}
function field(label,value){return`<div><span>${esc(label)}</span><strong>${esc(value||"—")}</strong></div>`}
function openRequest(id){current=requests.find(x=>String(x.id)===String(id));if(!current)return;const cat=current.insurance_category||"MOTOR",isMotor=cat==="MOTOR";$("modalTitle").textContent=`${current.full_name||"Customer"}'s Request`;$("modalSubtitle").textContent=isMotor?`${current.registration||"Vehicle"} · ${fmt(current.created_at)}`:`${current.insurance_type||"Non-Motor Insurance"} · ${fmt(current.created_at)}`;$("modalStatus").value=current.status||"new";$("customerDetails").innerHTML=field("Full Name",current.full_name)+field("Phone / WhatsApp",current.phone)+field("Email",current.email)+field("Contact Method",current.contact_method)+field("Submitted",fmt(current.created_at));
if(isMotor){
$("vehicleHeroLabel").textContent="MOTOR INSURANCE APPLICATION";
$("vehicleName").textContent=current.vehicle||"Vehicle Insurance";
$("vehicleSpecs").textContent=[current.registration,current.year?`Year ${current.year}`:"",current.cover||""].filter(Boolean).join(" · ")||"Insurance application";
$("vehicleDetails").innerHTML=field("Registration",current.registration)+field("Vehicle",current.vehicle)+field("Year",current.year)+field("Insurance Cover",current.cover)+field("Contact Method",current.contact_method)+field("Consent",current.consent?"Accepted":"Not Accepted");
$("enquiryDescription").style.display="none";$("enquiryDescription").innerHTML="";
$("documentSection").innerHTML=`<span>Customer Documents</span><div class="document-grid"><button class="document-btn" type="button" data-path="${esc(current.logbook_path)}"><i class="fa-solid fa-file-pdf"></i> Logbook</button><button class="document-btn" type="button" data-path="${esc(current.id_copy_path)}"><i class="fa-solid fa-id-card"></i> ID / Passport</button><button class="document-btn" type="button" data-path="${esc(current.kra_pin_path)}"><i class="fa-solid fa-file-shield"></i> KRA PIN</button></div>`;
}else{
$("vehicleHeroLabel").textContent="NON-MOTOR INSURANCE ENQUIRY";
$("vehicleName").textContent=current.insurance_type||"General Insurance Enquiry";
$("vehicleSpecs").textContent=[current.cover_required_date,current.location].filter(Boolean).join(" · ")||"Non-motor insurance enquiry";
$("vehicleDetails").innerHTML=field("Insurance Type",current.insurance_type)+field("When Cover Is Needed",current.cover_required_date)+field("Estimated Value",money(current.estimated_value))+field("Location",current.location)+field("Contact Method",current.contact_method)+field("Consent",current.consent?"Accepted":"Not Accepted");
if(current.description){$("enquiryDescription").style.display="block";$("enquiryDescription").innerHTML=`<span>What The Customer Needs</span><p>${esc(current.description)}</p>`}else{$("enquiryDescription").style.display="none";$("enquiryDescription").innerHTML=""}
const docs=Array.isArray(current.supporting_document_paths)?current.supporting_document_paths:[];
$("documentSection").innerHTML=docs.length?`<span>Supporting Documents</span><div class="document-grid">${docs.map((p,i)=>`<button class="document-btn" type="button" data-path="${esc(p)}"><i class="fa-solid fa-paperclip"></i> Document ${i+1}</button>`).join("")}</div>`:`<span>Supporting Documents</span><p class="no-documents">No supporting documents were uploaded with this enquiry.</p>`;
}
$("customerNotes").innerHTML=`<span>Customer Notes</span><p>${esc(current.notes||"No additional notes provided.")}</p>`;const p=String(current.phone||"").replace(/\D/g,"").replace(/^0/,"254");$("contactActions").innerHTML=`${p?`<a class="call-btn" href="tel:+${esc(p)}"><i class="fa-solid fa-phone"></i> Call Customer</a><a class="whatsapp-btn" target="_blank" rel="noopener" href="https://wa.me/${esc(p)}"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a>`:""}${current.email?`<a class="email-btn" href="mailto:${esc(current.email)}"><i class="fa-solid fa-envelope"></i> Email Customer</a>`:""}`;$("requestModal").classList.add("show");$("requestModal").setAttribute("aria-hidden","false");document.body.classList.add("locked");document.querySelectorAll("[data-path]").forEach(b=>b.onclick=()=>openDocument(b.dataset.path))}
async function openDocument(path){if(!path)return alert("Document not found.");const{data,error}=await supabase.storage.from("insurance-documents").createSignedUrl(path,300);if(error)return alert(error.message);window.open(data.signedUrl,"_blank","noopener,noreferrer")}
async function saveStatus(){if(!current)return;const status=$("modalStatus").value,{error}=await supabase.from("insurance_requests").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);current.status=status;const i=requests.findIndex(x=>String(x.id)===String(current.id));if(i>-1)requests[i]={...requests[i],status};stats();render()}
async function deleteRequest(){if(!current||!confirm(`Delete insurance request from ${current.full_name||"this customer"}?`))return;const docs=Array.isArray(current.supporting_document_paths)?current.supporting_document_paths:[];const paths=[current.logbook_path,current.id_copy_path,current.kra_pin_path,...docs].filter(Boolean),{error}=await supabase.from("insurance_requests").delete().eq("id",current.id);if(error)return alert(error.message);if(paths.length)await supabase.storage.from("insurance-documents").remove(paths);closeRequest();load()}
function closeRequest(){$("requestModal").classList.remove("show");$("requestModal").setAttribute("aria-hidden","true");document.body.classList.remove("locked");current=null}
grid.addEventListener("click",e=>{const card=e.target.closest(".request-card");if(card)openRequest(card.dataset.id)});$("searchInput").oninput=render;$("statusFilter").onchange=render;$("categoryFilter")&&($("categoryFilter").onchange=render);$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&current)closeRequest()});window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));requireAdmin("insurance").then(x=>{if(x){load();markSectionSeen("insurance");attachBadges()}});