import{supabase}from"./supabase.js";import{requireAdmin}from"./admin-guard.js";

const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat("en-KE").format(Math.round(n)),msg=(id,t)=>{$(id).textContent=t;$(id).classList.add("active");setTimeout(()=>$(id).classList.remove("active"),3500)},defaults={loan_default_vehicle_price:3000000,loan_default_deposit_pct:20,loan_default_interest_rate:13,loan_default_repayment_months:48,loan_min_deposit_pct:0,loan_max_deposit_pct:90,loan_min_repayment_months:1,loan_max_repayment_months:72,facility_fee:10000,min_deposit_pct:40,min_repayment_months:3,max_repayment_months:36};

async function loadContacts(){let{data,error}=await supabase.from("page_contacts").select("page_key,whatsapp,phone,email");if(error)return msg("error",error.message);(data||[]).forEach(c=>{let card=document.querySelector(`.contact-page[data-page="${c.page_key}"]`);if(!card)return;card.querySelector('[data-field="whatsapp"]').value=c.whatsapp||"";card.querySelector('[data-field="phone"]').value=c.phone||"";card.querySelector('[data-field="email"]').value=c.email||""})}

async function saveContact(card){let page=card.dataset.page,b=card.querySelector(".save-contact"),whatsapp=card.querySelector('[data-field="whatsapp"]').value.trim(),phone=card.querySelector('[data-field="phone"]').value.trim(),email=card.querySelector('[data-field="email"]').value.trim();b.disabled=true;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Saving...';let{error}=await supabase.from("page_contacts").upsert({page_key:page,whatsapp,phone,email,updated_at:new Date().toISOString()},{onConflict:"page_key"});b.disabled=false;b.innerHTML=`<i class="fa-solid fa-floppy-disk"></i> Save ${card.querySelector("h3").textContent}`;if(error)return msg("error",error.message);msg("success",`${card.querySelector("h3").textContent} contacts updated successfully.`)}

function loanValues(){return{loan_default_vehicle_price:Math.max(0,+$("loanDefaultPrice").value||0,0),loan_default_deposit_pct:Math.max(+$("loanDefaultDeposit").value||0,0),loan_default_interest_rate:Math.max(+$("loanDefaultInterest").value||0,0),loan_default_repayment_months:Math.max(1,+$("loanDefaultMonths").value||1),loan_min_deposit_pct:Math.max(0,+$("loanMinDeposit").value||0),loan_max_deposit_pct:Math.min(90,Math.max(0,+$("loanMaxDeposit").value||90)),loan_min_repayment_months:Math.max(1,+$("loanMinMonths").value||1),loan_max_repayment_months:Math.max(1,+$("loanMaxMonths").value||72)}}

function hpValues(){return{facility_fee:Math.max(0,+$("facilityFee").value||0),min_deposit_pct:Math.min(90,Math.max(0,+$("minDepositPct").value||0)),min_repayment_months:Math.max(1,+$("minRepaymentMonths").value||1),max_repayment_months:Math.max(1,+$("maxRepaymentMonths").value||1)}}

function loanPreview(){let v=loanValues(),p=v.loan_default_vehicle_price,d=v.loan_default_deposit_pct,r=v.loan_default_interest_rate,n=v.loan_default_repayment_months,l=p*(1-d/100),m=r?l*(r/1200)*Math.pow(1+r/1200,n)/(Math.pow(1+r/1200,n)-1):l/n,t=m*n;$("loanPreviewMonthly").textContent=`KES ${fmt(m)}`;$("loanPreviewAmount").textContent=`KES ${fmt(l)}`;$("loanPreviewInterest").textContent=`KES ${fmt(t-l)}`;$("loanPreviewTotal").textContent=`KES ${fmt(t)}`}

function hpPreview(){let v=hpValues(),vehicle=1000000,deposit=vehicle*v.min_deposit_pct/100,balance=vehicle-deposit,principal=balance/6,monthly=principal+v.facility_fee;$("previewFee").textContent=`KES ${fmt(v.facility_fee)}`;$("previewFee2").textContent=`KES ${fmt(v.facility_fee)}`;$("previewDeposit").textContent=`${v.min_deposit_pct}% · KES ${fmt(deposit)}`;$("previewBalance").textContent=`KES ${fmt(balance)}`;$("previewPrincipal").textContent=`KES ${fmt(principal)}`;$("previewExampleFee").textContent=`KES ${fmt(v.facility_fee)}`;$("previewInstallment").textContent=`KES ${fmt(monthly)}`}

function fillSettings(v){$("loanDefaultPrice").value=v.loan_default_vehicle_price;$("loanDefaultDeposit").value=v.loan_default_deposit_pct;$("loanDefaultInterest").value=v.loan_default_interest_rate;$("loanDefaultMonths").value=v.loan_default_repayment_months;$("loanMinDeposit").value=v.loan_min_deposit_pct;$("loanMaxDeposit").value=v.loan_max_deposit_pct;$("loanMinMonths").value=v.loan_min_repayment_months;$("loanMaxMonths").value=v.loan_max_repayment_months;$("facilityFee").value=v.facility_fee;$("minDepositPct").value=v.min_deposit_pct;$("minRepaymentMonths").value=v.min_repayment_months;$("maxRepaymentMonths").value=v.max_repayment_months;loanPreview();hpPreview()}

async function loadSettings(){let{data,error}=await supabase.from("financing_calculator_settings").select("*").eq("id",1).maybeSingle();if(error)return msg("error",error.message);fillSettings(data?{...defaults,...data}:defaults)}

async function saveSettings(){let l=loanValues(),h=hpValues();if(l.loan_default_deposit_pct<l.loan_min_deposit_pct||l.loan_default_deposit_pct>l.loan_max_deposit_pct)return msg("error","Monthly calculator default deposit must be within its allowed range.");if(l.loan_default_repayment_months<l.loan_min_repayment_months||l.loan_default_repayment_months>l.loan_max_repayment_months)return msg("error","Monthly calculator default duration must be within its allowed range.");if(l.loan_max_repayment_months<l.loan_min_repayment_months)return msg("error","Monthly calculator maximum months cannot be below minimum.");if(h.max_repayment_months<h.min_repayment_months)return msg("error","HP maximum repayment period cannot be below minimum.");let b=$("saveAllFormula");b.disabled=true;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Saving...';let{error}=await supabase.from("financing_calculator_settings").upsert({id:1,...l,...h,updated_at:new Date().toISOString()},{onConflict:"id"});b.disabled=false;b.innerHTML='<i class="fa-solid fa-floppy-disk"></i> Save All Calculator Settings';if(error)return msg("error",error.message);msg("success","Both financing calculators updated successfully.")}

async function resetSettings(){fillSettings(defaults);let b=$("resetAllFormula");b.disabled=true;b.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Resetting...';let{error}=await supabase.from("financing_calculator_settings").upsert({id:1,...defaults,updated_at:new Date().toISOString()},{onConflict:"id"});b.disabled=false;b.innerHTML='<i class="fa-solid fa-rotate-left"></i> Reset All Defaults';if(error)return msg("error",error.message);msg("success","Both financing calculators reset to defaults.")}

document.querySelectorAll(".contact-page").forEach(c=>c.querySelector(".save-contact")?.addEventListener("click",()=>saveContact(c)));
["loanDefaultPrice","loanDefaultDeposit","loanDefaultInterest","loanDefaultMonths","loanMinDeposit","loanMaxDeposit","loanMinMonths","loanMaxMonths"].forEach(id=>$(id)?.addEventListener("input",loanPreview));
["facilityFee","minDepositPct","minRepaymentMonths","maxRepaymentMonths"].forEach(id=>$(id)?.addEventListener("input",hpPreview));
$("saveAllFormula")?.addEventListener("click",saveSettings);
$("resetAllFormula")?.addEventListener("click",resetSettings);
$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};
$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};
$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.replace("auth.html")};
window.addEventListener("load",()=>setTimeout(()=>$("loader")?.classList.add("hide"),400));
requireAdmin("manageweb").then(async ok=>{if(!ok)return;await loadContacts();await loadSettings()});