import{supabase}from"./supabase.js";
import{requireAdmin}from"./admin-guard.js";const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),money=v=>Number(v||0).toLocaleString("en-KE"),fmt=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";let requests=[],current=null;

async function load(){$("loading").style.display="block";grid.innerHTML="";$("empty").style.display="none";$("error").classList.remove("active");try{let{data,error}=await supabase.from("vehicle_reservations").select("*,cars:car_id(id,make,model,year,price,stock_number,location,display_image_url,hero_image)").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}

function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>x.status==="new").length;$("progressRequests").textContent=requests.filter(x=>x.status==="in-progress").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length;$("cancelledRequests").textContent=requests.filter(x=>x.status==="cancelled").length}

function vehicle(x){let c=x.cars||{};return`${c.make||""} ${c.model||""} ${c.year||""}`.trim()||"Vehicle unavailable"}

function render(){let q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,o=$("sortFilter").value,l=requests.filter(x=>`${x.customer_name||""} ${x.customer_phone||""} ${x.customer_email||""} ${vehicle(x)} ${x.id_number||""} ${x.mpesa_reference||""}`.toLowerCase().includes(q)&&(s==="all"||x.status===s));l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):o==="deposit-high"?(b.deposit_amount||0)-(a.deposit_amount||0):o==="deposit-low"?(a.deposit_amount||0)-(b.deposit_amount||0):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}grid.innerHTML=l.map(x=>`<article class="request-card" onclick="openRequest('${x.id}')"><div class="request-top"><span class="request-status ${esc(x.status||"new")}">${esc(x.status||"new")}</span><small>${fmt(x.created_at)}</small></div><h3>${esc(x.customer_name)}</h3><p><i class="fa-solid fa-phone"></i> ${esc(x.customer_phone)}</p><p><i class="fa-solid fa-car"></i> ${esc(vehicle(x))}</p><div class="request-meta"><span>${esc(x.mpesa_reference||"Payment pending")}</span><strong>KES ${money(x.deposit_amount)}</strong></div><div class="request-bottom"><span>${esc((x.cars||{}).stock_number||"Reservation")}</span><button type="button" onclick="event.stopPropagation();openRequest('${x.id}')">View Request <i class="fa-solid fa-arrow-right"></i></button></div></article>`).join("")}

window.openRequest=id=>{current=requests.find(x=>x.id===id);if(!current)return;let c=current.cars||{};$("modalTitle").textContent=`${current.customer_name}'s Reservation`;$("modalStatus").value=current.status||"new";$("modalBody").innerHTML=`<div class="vehicle-box">${c.display_image_url||c.hero_image?`<img src="${esc(c.display_image_url||c.hero_image)}" alt="${esc(vehicle(current))}">`:`<div class="vehicle-placeholder"><i class="fa-solid fa-car"></i></div>`}<div><span>Reserved Vehicle</span><strong>${esc(vehicle(current))}</strong><small>${esc(c.stock_number||"No stock number")} · KES ${money(c.price)}</small></div></div><div class="detail-grid"><div><span>Full Name</span><strong>${esc(current.customer_name)}</strong></div><div><span>Phone / WhatsApp</span><strong>${esc(current.customer_phone)}</strong></div><div><span>Email</span><strong>${esc(current.customer_email||"—")}</strong></div><div><span>ID / Passport</span><strong>${esc(current.id_number)}</strong></div><div><span>Deposit Amount</span><strong>KES ${money(current.deposit_amount)}</strong></div><div><span>M-PESA Reference</span><strong>${esc(current.mpesa_reference||"Pending")}</strong></div><div><span>Vehicle Location</span><strong>${esc(c.location||"—")}</strong></div><div><span>Submitted</span><strong>${fmt(current.created_at)}</strong></div></div><div class="contact-actions"><a href="tel:${esc(current.customer_phone)}"><i class="fa-solid fa-phone"></i> Call Customer</a><a target="_blank" href="https://wa.me/254${String(current.customer_phone||"").replace(/\\D/g,"").replace(/^254/,"")}"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a>${current.customer_email?`<a href="mailto:${esc(current.customer_email)}"><i class="fa-solid fa-envelope"></i> Email</a>`:""}</div><div class="notes"><span>Notes</span><p>${esc(current.notes||"No additional notes.")}</p></div>`;$("requestModal").classList.add("show");document.body.classList.add("locked")}

async function saveStatus(){if(!current)return;let status=$("modalStatus").value,{error}=await supabase.from("vehicle_reservations").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}

async function deleteRequest(){if(!current||!confirm(`Delete reservation from ${current.customer_name}?`))return;let{error}=await supabase.from("vehicle_reservations").delete().eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}

function closeRequest(){$("requestModal").classList.remove("show");document.body.classList.remove("locked");current=null}

$("searchInput").oninput=render;$("statusFilter").onchange=render;$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));requireAdmin("reservations").then(x=>x&&load());