import{supabase}from"./supabase.js";const $=id=>document.getElementById(id),grid=$("requestsGrid"),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),money=v=>Number(v||0).toLocaleString("en-KE"),date=v=>v?new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}):"—";let requests=[],current=null;

async function load(){$("loading").style.display="block";grid.innerHTML="";$("empty").style.display="none";$("error").classList.remove("active");try{let{data,error}=await supabase.from("sell_car_requests").select("*").order("created_at",{ascending:false});if(error)throw error;requests=data||[];stats();render()}catch(e){$("error").textContent=e.message;$("error").classList.add("active")}finally{$("loading").style.display="none"}}

function stats(){$("totalRequests").textContent=requests.length;$("newRequests").textContent=requests.filter(x=>(x.status||"new")==="new").length;$("contactedRequests").textContent=requests.filter(x=>x.status==="contacted").length;$("inspectedRequests").textContent=requests.filter(x=>x.status==="inspected").length;$("completedRequests").textContent=requests.filter(x=>x.status==="completed").length}

function render(){let q=$("searchInput").value.toLowerCase().trim(),s=$("statusFilter").value,o=$("sortFilter").value,l=requests.filter(x=>{let t=`${x.full_name||""} ${x.phone||""} ${x.email||""} ${x.registration||""} ${x.make||""} ${x.model||""} ${x.location||""}`.toLowerCase();return(!q||t.includes(q))&&(s==="all"||(x.status||"new")===s)});l.sort((a,b)=>o==="oldest"?new Date(a.created_at)-new Date(b.created_at):o==="price-high"?(b.asking_price||0)-(a.asking_price||0):o==="price-low"?(a.asking_price||0)-(b.asking_price||0):new Date(b.created_at)-new Date(a.created_at));if(!l.length){$("empty").style.display="block";return}grid.innerHTML=l.map(x=>{let st=x.status||"new";return`<article class="request-card" onclick="openRequest('${x.id}')"><div class="request-top"><span class="request-status ${esc(st)}">${esc(st)}</span><small>${date(x.created_at)}</small></div><h3>${esc(x.make)} ${esc(x.model)} ${esc(x.year)}</h3><p><i class="fa-solid fa-user"></i> ${esc(x.full_name)}</p><p><i class="fa-solid fa-phone"></i> ${esc(x.phone)}</p><p><i class="fa-solid fa-location-dot"></i> ${esc(x.location)}</p><div class="request-meta"><span>${esc(x.registration)} · ${Number(x.mileage||0).toLocaleString()} KM</span><strong>KES ${money(x.asking_price)}</strong></div><div class="request-bottom"><span>${esc(x.condition||"Condition —")}</span><button type="button" onclick="event.stopPropagation();openRequest('${x.id}')">View Request <i class="fa-solid fa-arrow-right"></i></button></div></article>`}).join("")}

async function files(id){let{data,error}=await supabase.from("sell_car_files").select("*").eq("request_id",id).order("created_at",{ascending:true});if(error)throw error;return data||[]}

window.openRequest=async id=>{current=requests.find(x=>x.id===id);if(!current)return;$("modalTitle").textContent=`${current.make||""} ${current.model||""} — ${current.full_name||"Customer"}`;$("modalStatus").value=current.status||"new";try{let fs=await files(id),html=`<div class="detail-grid"><div><span>Seller</span><strong>${esc(current.full_name)}</strong></div><div><span>Phone</span><strong>${esc(current.phone)}</strong></div><div><span>Email</span><strong>${esc(current.email||"—")}</strong></div><div><span>ID / Passport</span><strong>${esc(current.id_number)}</strong></div><div><span>Location</span><strong>${esc(current.location)}</strong></div><div><span>Contact Time</span><strong>${esc(current.contact_time||"Any Time")}</strong></div><div><span>Vehicle</span><strong>${esc(current.make)} ${esc(current.model)} ${esc(current.year)}</strong></div><div><span>Registration</span><strong>${esc(current.registration)}</strong></div><div><span>Colour</span><strong>${esc(current.colour)}</strong></div><div><span>Mileage</span><strong>${Number(current.mileage||0).toLocaleString()} KM</strong></div><div><span>Transmission</span><strong>${esc(current.transmission)}</strong></div><div><span>Fuel Type</span><strong>${esc(current.fuel_type)}</strong></div><div><span>Engine</span><strong>${esc(current.engine_cc)} CC</strong></div><div><span>Body Type</span><strong>${esc(current.body_type)}</strong></div><div><span>Condition</span><strong>${esc(current.condition)}</strong></div><div><span>Accident History</span><strong>${esc(current.accident_history)}</strong></div><div><span>Asking Price</span><strong>KES ${money(current.asking_price)}</strong></div><div><span>Negotiable</span><strong>${esc(current.negotiable)}</strong></div><div><span>Outstanding Loan</span><strong>${esc(current.loan)}</strong></div><div><span>Trade-In</span><strong>${esc(current.trade_in)}</strong></div><div><span>Submitted</span><strong>${date(current.created_at)}</strong></div></div><div class="notes"><span>Additional Information</span><p>${esc(current.additional_info||"No additional information.")}</p></div>`;if(fs.length)html+=`<h3 class="files-title">Submitted Documents & Photos (${fs.length})</h3><div class="files-grid">${fs.map(f=>{let url=supabase.storage.from("sell-car-files").getPublicUrl(f.storage_path).data.publicUrl;return`<a class="file-link" href="${esc(url)}" target="_blank" rel="noopener"><i class="fa-solid ${f.file_type?.startsWith("video/")?"fa-video":f.file_type==="application/pdf"?"fa-file-pdf":"fa-image"}"></i>${esc(f.field_name||f.file_name)}</a>`}).join("")}</div>`;$("modalBody").innerHTML=html;$("requestModal").classList.add("show");document.body.classList.add("locked")}catch(e){alert(e.message)}};

async function saveStatus(){if(!current)return;let status=$("modalStatus").value,{error}=await supabase.from("sell_car_requests").update({status,updated_at:new Date().toISOString()}).eq("id",current.id);if(error)return alert(error.message);closeRequest();load()}

async function deleteRequest(){if(!current||!confirm(`Delete sell request from ${current.full_name||"this customer"}?`))return;try{let{data:fs}=await supabase.from("sell_car_files").select("storage_path").eq("request_id",current.id),paths=(fs||[]).map(x=>x.storage_path);if(paths.length){let{error}=await supabase.storage.from("sell-car-files").remove(paths);if(error)throw error}let{error}=await supabase.from("sell_car_requests").delete().eq("id",current.id);if(error)throw error;closeRequest();load()}catch(e){alert(e.message)}}

function closeRequest(){$("requestModal").classList.remove("show");document.body.classList.remove("locked");current=null}

$("searchInput").oninput=render;$("statusFilter").onchange=render;$("sortFilter").onchange=render;$("refreshBtn").onclick=load;$("saveStatus").onclick=saveStatus;$("deleteRequest").onclick=deleteRequest;$("closeRequest").onclick=closeRequest;$("closeRequestBg").onclick=closeRequest;$("menu").onclick=()=>{$("sidebar").classList.add("open");$("overlay").classList.add("show")};$("closeMenu").onclick=$("overlay").onclick=()=>{$("sidebar").classList.remove("open");$("overlay").classList.remove("show")};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.href="auth.html"};window.addEventListener("load",()=>setTimeout(()=>$("loader").classList.add("hide"),450));load();